; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; RUN: opt -passes=loop-vectorize -force-vector-width=4 -S %s | FileCheck %s

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define i1 @fn(ptr %nno) #0 {
; CHECK-LABEL: define i1 @fn(
; CHECK-SAME: ptr [[NNO:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw i32, ptr [[NNO]], i64 10
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i64 -3
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i64 -7
; CHECK-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = load <4 x i32>, ptr [[TMP1]], align 4
; CHECK-NEXT:    [[WIDE_LOAD1:%.*]] = load <4 x i32>, ptr [[TMP2]], align 4
; CHECK-NEXT:    [[REVERSE1:%.*]] = shufflevector <4 x i32> [[WIDE_MASKED_LOAD]], <4 x i32> poison, <4 x i32> <i32 3, i32 2, i32 1, i32 0>
; CHECK-NEXT:    [[REVERSE2:%.*]] = shufflevector <4 x i32> [[WIDE_LOAD1]], <4 x i32> poison, <4 x i32> <i32 3, i32 2, i32 1, i32 0>
; CHECK-NEXT:    [[TMP7:%.*]] = shl <4 x i32> [[REVERSE1]], splat (i32 1)
; CHECK-NEXT:    [[TMP4:%.*]] = shl <4 x i32> [[REVERSE2]], splat (i32 1)
; CHECK-NEXT:    [[TMP8:%.*]] = urem <4 x i32> [[TMP7]], splat (i32 10)
; CHECK-NEXT:    [[TMP6:%.*]] = urem <4 x i32> [[TMP4]], splat (i32 10)
; CHECK-NEXT:    [[PREDPHI:%.*]] = select <4 x i1> <i1 true, i1 false, i1 true, i1 false>, <4 x i32> [[TMP8]], <4 x i32> [[REVERSE1]]
; CHECK-NEXT:    [[PREDPHI3:%.*]] = select <4 x i1> <i1 true, i1 false, i1 true, i1 false>, <4 x i32> [[TMP6]], <4 x i32> [[REVERSE2]]
; CHECK-NEXT:    [[TMP10:%.*]] = or <4 x i32> [[PREDPHI]], zeroinitializer
; CHECK-NEXT:    br label [[MIDDLE_BLOCK:%.*]]
; CHECK:       middle.block:
; CHECK-NEXT:    [[TMP12:%.*]] = or <4 x i32> [[PREDPHI3]], [[TMP10]]
; CHECK-NEXT:    [[TMP14:%.*]] = call i32 @llvm.vector.reduce.or.v4i32(<4 x i32> [[TMP12]])
; CHECK-NEXT:    br label [[FOR_INC35:%.*]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    br label [[LOOP_HEADER:%.*]]
; CHECK:       loop.header:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 2, [[FOR_INC35]] ], [ [[IV_NEXT:%.*]], [[LOOP_LATCH:%.*]] ]
; CHECK-NEXT:    [[SUM_01:%.*]] = phi i32 [ [[TMP14]], [[FOR_INC35]] ], [ [[SUM_1:%.*]], [[LOOP_LATCH]] ]
; CHECK-NEXT:    [[REM4:%.*]] = and i64 [[IV]], 1
; CHECK-NEXT:    [[CMP21:%.*]] = icmp eq i64 [[REM4]], 0
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw i32, ptr [[NNO]], i64 [[IV]]
; CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[GEP]], align 4
; CHECK-NEXT:    br i1 [[CMP21]], label [[IF_THEN:%.*]], label [[LOOP_LATCH]]
; CHECK:       if.then:
; CHECK-NEXT:    [[MUL:%.*]] = shl i32 [[TMP9]], 1
; CHECK-NEXT:    [[REM27:%.*]] = urem i32 [[MUL]], 10
; CHECK-NEXT:    br label [[LOOP_LATCH]]
; CHECK:       loop.latch:
; CHECK-NEXT:    [[REM27_PN:%.*]] = phi i32 [ [[REM27]], [[IF_THEN]] ], [ [[TMP9]], [[LOOP_HEADER]] ]
; CHECK-NEXT:    [[SUM_1]] = or i32 [[REM27_PN]], [[SUM_01]]
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], -1
; CHECK-NEXT:    [[CMP19_NOT:%.*]] = icmp eq i64 [[IV]], 0
; CHECK-NEXT:    br i1 [[CMP19_NOT]], label [[EXIT:%.*]], label [[LOOP_HEADER]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       exit:
; CHECK-NEXT:    [[SUM_1_LCSSA:%.*]] = phi i32 [ [[SUM_1]], [[LOOP_LATCH]] ]
; CHECK-NEXT:    [[CMP41:%.*]] = icmp eq i32 [[SUM_1_LCSSA]], 0
; CHECK-NEXT:    ret i1 [[CMP41]]
;
entry:
  br label %loop.header

loop.header:
  %iv = phi i64 [ 10, %entry ], [ %iv.next, %loop.latch ]
  %sum.01 = phi i32 [ 0, %entry ], [ %sum.1, %loop.latch ]
  %rem4 = and i64 %iv, 1
  %cmp21 = icmp eq i64 %rem4, 0
  %gep = getelementptr inbounds nuw i32, ptr %nno, i64 %iv
  %0 = load i32, ptr %gep, align 4
  br i1 %cmp21, label %if.then, label %loop.latch

if.then:
  %mul = shl i32 %0, 1
  %rem27 = urem i32 %mul, 10
  br label %loop.latch

loop.latch:
  %rem27.pn = phi i32 [ %rem27, %if.then ], [ %0, %loop.header ]
  %sum.1 = or i32 %rem27.pn, %sum.01
  %iv.next = add nsw i64 %iv, -1
  %cmp19.not = icmp eq i64 %iv, 0
  br i1 %cmp19.not, label %exit, label %loop.header

exit:
  %sum.1.lcssa = phi i32 [ %sum.1, %loop.latch ]
  %cmp41 = icmp eq i32 %sum.1.lcssa, 0
  ret i1 %cmp41
}

attributes #0 = { "target-features"="+avx" }
