; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=loop-vectorize -mtriple=s390x-ibm-linux -mcpu=z13 -force-vector-width=2 -S %s | FileCheck %s

; Test case from PR44020.

; In func_21, %rec forms a first order recurrence and we predicate to avoid
; scalar iteration overhead for a low trip count loop. Make sure we pick
; the correct insertion point when fixing first order recurrences.

@A = external global [5 x i32], align 4
@B = external global [5 x i32], align 4

define void @func_21() {
; CHECK-LABEL: @func_21(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[VECTOR_RECUR:%.*]] = load <2 x i32>, ptr @A, align 4
; CHECK-NEXT:    [[TMP12:%.*]] = load <2 x i32>, ptr getelementptr inbounds (i32, ptr @A, i64 2), align 4
; CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <2 x i32> zeroinitializer, <2 x i32> [[VECTOR_RECUR]], <2 x i32> <i32 1, i32 2>
; CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <2 x i32> [[VECTOR_RECUR]], <2 x i32> [[TMP12]], <2 x i32> <i32 1, i32 2>
; CHECK-NEXT:    store <2 x i32> [[TMP0]], ptr @B, align 4
; CHECK-NEXT:    store <2 x i32> [[TMP13]], ptr getelementptr inbounds (i32, ptr @B, i64 2), align 4
; CHECK-NEXT:    br label [[PRED_STORE_CONTINUE:%.*]]
; CHECK:       middle.block:
; CHECK-NEXT:    [[VECTOR_RECUR_EXTRACT:%.*]] = extractelement <2 x i32> [[TMP12]], i64 1
; CHECK-NEXT:    br label [[PRED_STORE_CONTINUE4:%.*]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[REC:%.*]] = phi i32 [ [[VECTOR_RECUR_EXTRACT]], [[PRED_STORE_CONTINUE4]] ], [ [[LV:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 4, [[PRED_STORE_CONTINUE4]] ], [ [[INDVARS_IV_NEXT:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[A_PTR:%.*]] = getelementptr inbounds [5 x i32], ptr @A, i64 0, i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[LV]] = load i32, ptr [[A_PTR]], align 4
; CHECK-NEXT:    [[B_PTR:%.*]] = getelementptr inbounds [5 x i32], ptr @B, i64 0, i64 [[INDVARS_IV]]
; CHECK-NEXT:    store i32 [[REC]], ptr [[B_PTR]], align 4
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 5
; CHECK-NEXT:    br i1 [[EXITCOND]], label [[EXIT:%.*]], label [[LOOP]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %rec = phi i32 [ 0, %entry], [ %lv, %loop ]
  %indvars.iv = phi i64 [ 0, %entry], [ %indvars.iv.next, %loop ]
  %A.ptr= getelementptr inbounds [5 x i32], ptr @A, i64 0, i64 %indvars.iv
  %lv = load i32, ptr %A.ptr, align 4
  %B.ptr = getelementptr inbounds [5 x i32], ptr @B, i64 0, i64 %indvars.iv
  store i32 %rec, ptr %B.ptr, align 4
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond = icmp eq i64 %indvars.iv.next, 5
  br i1 %exitcond, label %exit, label %loop

exit:
  ret void
}
