; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --version 6
; RUN: opt -p loop-vectorize -mtriple=aarch64-linux-gnu -S %s | FileCheck %s

define void @low_trip_count_small(i32 %x, ptr %dst) {
; CHECK-LABEL: define void @low_trip_count_small(
; CHECK-SAME: i32 [[X:%.*]], ptr [[DST:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[SMAX:%.*]] = call i32 @llvm.smax.i32(i32 [[X]], i32 1)
; CHECK-NEXT:    [[UMIN:%.*]] = call i32 @llvm.umin.i32(i32 [[SMAX]], i32 4)
; CHECK-NEXT:    [[TMP0:%.*]] = zext nneg i32 [[SMAX]] to i64
; CHECK-NEXT:    [[UMIN1:%.*]] = call i64 @llvm.umin.i64(i64 [[TMP0]], i64 4)
; CHECK-NEXT:    [[TMP6:%.*]] = icmp ult i64 [[UMIN1]], 4
; CHECK-NEXT:    br i1 [[TMP6]], label %[[PRED_STORE_IF:.*]], label %[[PRED_STORE_CONTINUE:.*]]
; CHECK:       [[PRED_STORE_CONTINUE]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[UMIN1]], 4
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[UMIN1]], [[N_MOD_VF]]
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[DST]], i64 [[N_VEC]]
; CHECK-NEXT:    [[TMP2:%.*]] = trunc i64 [[N_VEC]] to i32
; CHECK-NEXT:    br label %[[PRED_STORE_IF5:.*]]
; CHECK:       [[PRED_STORE_IF5]]:
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[DST]], i64 1
; CHECK-NEXT:    store <4 x i8> zeroinitializer, ptr [[TMP3]], align 1
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE6:.*]]
; CHECK:       [[PRED_STORE_CONTINUE6]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[UMIN1]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[PRED_STORE_IF]]
; CHECK:       [[PRED_STORE_IF]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi ptr [ [[TMP1]], %[[PRED_STORE_CONTINUE6]] ], [ [[DST]], %[[ENTRY]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL2:%.*]] = phi i32 [ [[TMP2]], %[[PRED_STORE_CONTINUE6]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE8:.*]]
; CHECK:       [[PRED_STORE_CONTINUE8]]:
; CHECK-NEXT:    [[NEXT_GEP4:%.*]] = phi ptr [ [[BC_RESUME_VAL]], %[[PRED_STORE_IF]] ], [ [[TMP13:%.*]], %[[PRED_STORE_CONTINUE8]] ]
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ [[BC_RESUME_VAL2]], %[[PRED_STORE_IF]] ], [ [[IV_NEXT:%.*]], %[[PRED_STORE_CONTINUE8]] ]
; CHECK-NEXT:    [[TMP13]] = getelementptr i8, ptr [[NEXT_GEP4]], i64 1
; CHECK-NEXT:    store i8 0, ptr [[TMP13]], align 1
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp eq i32 [[IV_NEXT]], [[UMIN]]
; CHECK-NEXT:    br i1 [[EXITCOND]], label %[[EXIT]], label %[[PRED_STORE_CONTINUE8]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %smax = call i32 @llvm.smax.i32(i32 %x, i32 1)
  %umin = call i32 @llvm.umin.i32(i32 %smax, i32 4)
  br label %loop

loop:
  %ptr = phi ptr [ %dst, %entry ], [ %ptr.next, %loop ]
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %ptr.next = getelementptr i8, ptr %ptr, i64 1
  store i8 0, ptr %ptr.next
  %iv.next = add i32 %iv, 1
  %exitcond = icmp eq i32 %iv.next, %umin
  br i1 %exitcond, label %exit, label %loop

exit:
  ret void
}


define ptr @low_trip_count_small_with_live_out(i32 %x, ptr %dst) {
; CHECK-LABEL: define ptr @low_trip_count_small_with_live_out(
; CHECK-SAME: i32 [[X:%.*]], ptr [[DST:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[SMAX:%.*]] = call i32 @llvm.smax.i32(i32 [[X]], i32 1)
; CHECK-NEXT:    [[UMIN:%.*]] = call i32 @llvm.umin.i32(i32 [[SMAX]], i32 4)
; CHECK-NEXT:    [[TMP0:%.*]] = zext nneg i32 [[SMAX]] to i64
; CHECK-NEXT:    [[UMIN1:%.*]] = call i64 @llvm.umin.i64(i64 [[TMP0]], i64 4)
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[UMIN1]], 4
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[PRED_STORE_CONTINUE8:.*]], label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[UMIN1]], 4
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[UMIN1]], [[N_MOD_VF]]
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[DST]], i64 [[N_VEC]]
; CHECK-NEXT:    [[TMP2:%.*]] = trunc i64 [[N_VEC]] to i32
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[PTR_NEXT:%.*]] = getelementptr i8, ptr [[DST]], i64 1
; CHECK-NEXT:    store <4 x i8> zeroinitializer, ptr [[PTR_NEXT]], align 1
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE6:.*]]
; CHECK:       [[PRED_STORE_CONTINUE6]]:
; CHECK-NEXT:    [[TMP11:%.*]] = icmp eq i64 [[UMIN1]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP11]], label %[[PRED_STORE_IF7:.*]], label %[[PRED_STORE_CONTINUE8]]
; CHECK:       [[PRED_STORE_CONTINUE8]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi ptr [ [[TMP1]], %[[PRED_STORE_CONTINUE6]] ], [ [[DST]], %[[ENTRY]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL2:%.*]] = phi i32 [ [[TMP2]], %[[PRED_STORE_CONTINUE6]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    br label %[[PRED_STORE_IF9:.*]]
; CHECK:       [[PRED_STORE_IF9]]:
; CHECK-NEXT:    [[NEXT_GEP4:%.*]] = phi ptr [ [[BC_RESUME_VAL]], %[[PRED_STORE_CONTINUE8]] ], [ [[TMP14:%.*]], %[[PRED_STORE_IF9]] ]
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ [[BC_RESUME_VAL2]], %[[PRED_STORE_CONTINUE8]] ], [ [[IV_NEXT:%.*]], %[[PRED_STORE_IF9]] ]
; CHECK-NEXT:    [[TMP14]] = getelementptr i8, ptr [[NEXT_GEP4]], i64 1
; CHECK-NEXT:    store i8 0, ptr [[TMP14]], align 1
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp eq i32 [[IV_NEXT]], [[UMIN]]
; CHECK-NEXT:    br i1 [[EXITCOND]], label %[[PRED_STORE_IF7]], label %[[PRED_STORE_IF9]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK:       [[PRED_STORE_IF7]]:
; CHECK-NEXT:    [[PTR_NEXT_LCSSA:%.*]] = phi ptr [ [[TMP14]], %[[PRED_STORE_IF9]] ], [ [[TMP1]], %[[PRED_STORE_CONTINUE6]] ]
; CHECK-NEXT:    ret ptr [[PTR_NEXT_LCSSA]]
;
entry:
  %smax = call i32 @llvm.smax.i32(i32 %x, i32 1)
  %umin = call i32 @llvm.umin.i32(i32 %smax, i32 4)
  br label %loop

loop:
  %ptr = phi ptr [ %dst, %entry ], [ %ptr.next, %loop ]
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %ptr.next = getelementptr i8, ptr %ptr, i64 1
  store i8 0, ptr %ptr.next
  %iv.next = add i32 %iv, 1
  %exitcond = icmp eq i32 %iv.next, %umin
  br i1 %exitcond, label %exit, label %loop

exit:
  ret ptr %ptr.next
}
